name: Build

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_TYPE: Release
  IMHEX_VERSION: "1.38.1"

jobs:
  windows:
    if: false
    runs-on: windows-latest
    name: Windows
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install SDK
        id: install_sdk
        uses: WerWolv/imhex-download-sdk@v1.38.1

      - name: Build
        run: |
          mkdir build && cd build
          IMHEX_SDK_PATH="${{ steps.install_sdk.outputs.sdk_path }}"      \
            cmake -G Ninja                                                \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}                      \
            -DCMAKE_INSTALL_PREFIX="./install"                            \
            ..
          cmake --build .
          cmake --install .

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-build
          path: build/install

  macos:
    if: false
    runs-on: macos-latest
    name: MacOS
    defaults:
      run:
        shell: bash {0}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install SDK
        id: install_sdk
        uses: WerWolv/imhex-download-sdk@v1.38.1

      - name: Build
        run: |
          mkdir build && cd build
          CC=$(brew --prefix gcc@15)/bin/gcc-15                                                         \
          CXX=$(brew --prefix gcc@15)/bin/g++-15                                                        \
          OBJC=$(brew --prefix llvm)/bin/clang                                                          \
          OBJCXX=$(brew --prefix llvm)/bin/clang++                                                      \
          PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig"     \
          IMHEX_SDK_PATH="${{ steps.install_sdk.outputs.sdk_path }}"                                    \
            cmake                                                                                       \
            -G Ninja                                                                                    \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}                                                    \
            -DCMAKE_INSTALL_PREFIX="./install"                                                          \
            ..
          cmake --build .
          cmake --install .

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: macos-build
          path: build/install
